[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "frontmatter>=3.0.8",
    "pyaml>=25.7.0",
]
